### ISSUE TITLE
Question about your challenge

### ISSUE THREAD

**Issue by jollerw** [gruellan/google-foobar-challenge-2020#1]
Hi! Just out of curiosity: Did you hear back from any Google recruiter after finishing the foo bar challenge? Thanks!

**Comment by gruellan** [comment]
Hey! I only finished up to Level 4-2 and no I wasn't contacted :( They did take my contact details and resume after completing Level 3 though

**Comment by jollerw** [comment]
OK. Thanks a lot for sharing with me!
